#!/usr/bin/env bash
# Print a Nix derivation for an agent-recall release, for babarot/nur-packages.
# Usage: nix-derivation.sh <version> <checksums.txt>
set -euo pipefail

version=$1
checksums=$2

sha() {
  local sum
  sum=$(awk -v f="$1" '$2 == f { print $1 }' "$checksums")
  if [[ -z $sum ]]; then
    echo "no checksum for $1 in $checksums" >&2
    exit 1
  fi
  echo "$sum"
}

cat <<EOF
# This file was generated by agent-recall's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "${version}";
  base = "https://github.com/babarot/agent-recall/releases/download/\${version}";
  assets = {
    aarch64-darwin = {
      name = "agent-recall-darwin-arm64";
      sha256 = "$(sha agent-recall-darwin-arm64)";
    };
    x86_64-darwin = {
      name = "agent-recall-darwin-x86_64";
      sha256 = "$(sha agent-recall-darwin-x86_64)";
    };
    aarch64-linux = {
      name = "agent-recall-linux-arm64";
      sha256 = "$(sha agent-recall-linux-arm64)";
    };
    x86_64-linux = {
      name = "agent-recall-linux-x86_64";
      sha256 = "$(sha agent-recall-linux-x86_64)";
    };
  };
  asset = assets.\${system} or (throw "agent-recall: unsupported system \${system}");
  plugin = fetchurl {
    url = "\${base}/agent-recall-plugin.tar.gz";
    sha256 = "$(sha agent-recall-plugin.tar.gz)";
  };
in
stdenvNoCC.mkDerivation {
  pname = "agent-recall";
  inherit version;

  src = fetchurl {
    url = "\${base}/\${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # deno compile appends the program to the executable; stripping or
  # other fixups would break it
  dontFixup = true;

  # The Claude Code plugin (MCP server, SessionEnd hook, skills) lands in
  # share/claude-plugin/agent-recall; its skills are under skills/<name>
  installPhase = ''
    install -Dm755 \$src \$out/bin/agent-recall
    mkdir -p \$out/share/claude-plugin/agent-recall
    tar -xzf \${plugin} -C \$out/share/claude-plugin/agent-recall
  '';

  meta = {
    description = "Archive and search coding agent sessions";
    homepage = "https://github.com/babarot/agent-recall";
    mainProgram = "agent-recall";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
EOF
