#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Reads all files from ui/dist/ and generates src/ui_assets.ts
 * with the file contents embedded as base64-encoded Uint8Array.
 */

import { walk } from "https://deno.land/std@0.224.0/fs/walk.ts";
import { encodeBase64 } from "https://deno.land/std@0.224.0/encoding/base64.ts";
import { relative } from "https://deno.land/std@0.224.0/path/mod.ts";

const DIST_DIR = new URL("../ui/dist", import.meta.url).pathname;
const OUTPUT = new URL("../src/ui_assets.ts", import.meta.url).pathname;

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
};

function getContentType(path: string): string {
  for (const [ext, type] of Object.entries(CONTENT_TYPES)) {
    if (path.endsWith(ext)) return type;
  }
  return "application/octet-stream";
}

const entries: string[] = [];

for await (const entry of walk(DIST_DIR, { includeFiles: true, includeDirs: false })) {
  const rel = "/" + relative(DIST_DIR, entry.path);
  const content = await Deno.readFile(entry.path);
  const b64 = encodeBase64(content);
  const contentType = getContentType(rel);
  entries.push(`  ["${rel}", { data: "${b64}", contentType: "${contentType}" }]`);
}

const code = `// AUTO-GENERATED by scripts/embed_ui.ts — do not edit
import { decodeBase64 } from "https://deno.land/std@0.224.0/encoding/base64.ts";

const RAW: Map<string, { data: string; contentType: string }> = new Map([
${entries.join(",\n")}
]);

export function getAsset(path: string): { content: Uint8Array; contentType: string } | null {
  const entry = RAW.get(path);
  if (!entry) return null;
  return { content: decodeBase64(entry.data), contentType: entry.contentType };
}
`;

await Deno.writeTextFile(OUTPUT, code);
console.log(`Generated ${OUTPUT} with ${entries.length} assets.`);
